[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_twitter = "CGK64Wd5gmKZKMEF9urqNz9ac2hziZYQxsin8Y8gsRHo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/serhatonal/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
sayhello = "echo 'Hello World!'"
